---
title: "BAS 240 Final, Casino Time!"
output: html_notebook
---

```{r}
### First the dice!
die <- 1:6

ls()

sample(x = 1:4, size = 2)
sample(x = die, size = 1)

dice <- sample(die, size = 2, replace = TRUE)

sum(dice)

roll <- function() {
  die <- 1:6
  dice <- sample(die, size = 2, replace = TRUE)
  sum(dice) }

roll()


roll2 <- function(bones) {
  dice <- sample(bones, size = 2, replace = TRUE)
  sum(dice) }

roll2(bones = 1:6)

roll2 <- function(bones = 1:6) {
  dice <- sample(bones, size = 2, replace = TRUE)
  sum(dice) }

roll2()

library(ggplot2)

myroll <- function() {
  die <- 1:6
  dice <- sample(die, size = 2, replace = TRUE,
                 prob = c(1/8, 1/8, 1/8, 1/8, 1/8, 3/8))
  sum(dice) }

myrolls <- replicate(10000, myroll())
qplot(myrolls, binwidth = 1)

### Okay, that was weighted dice! of course, if it was house
### rules the 3/8 would be on the first numbers
####################################################################
```

```{r}
### Card time!
hand <- c("ace", "king", "queen", "jack", "ten")

df <- data.frame(face = c("ace", "two", "six"),  
                 suit = c("clubs", "clubs", "clubs"), 
                 value = c(1, 2, 3))
df

df <- data.frame(face = c("ace", "two", "six"),  
                 suit = c("clubs", "clubs", "clubs"), 
                 value = c(1, 2, 3),
                 stringsAsFactors = FALSE)
df
deck <- read.csv("C:/Users/18033/Desktop/School Schtuff/Current Semester/Fall 2021/BAS 240/deck.csv")


?write.csv
deck[ , ]

deck[1, c(1, 2, 3)]
new <- deck[1, c(1, 2, 3)]
new


deal <- function(cards) {
  cards[1, ] }
#lol
deal(deck)

deck2 <- deck[1:52, ]

head(deck2)

deck3 <- deck[c(2, 1, 3:52), ]

random <- sample(1:52, size = 52)
deck4 <- deck[random, ]
head(deck4)


shuffle <- function(cards) {
  random <- sample(1:52, size = 52)
  cards[random, ] }

deal(deck)

deck2 <- shuffle(deck)

deal(deck2)
# ch 7 now modifying our deck
deck2 <- deck

deck2$new <- 1:52
head(deck2)
deck2$new <- NULL
head(deck2)

deck2[c(13, 26, 39, 52), ]
deck2$value[c(13, 26, 39, 52)]
deck2$value[c(13, 26, 39, 52)] <- 14
head(deck2, 13)

deck2$face
sum(deck2$face == "ace")

deck3$face == "ace"
deck3$value[deck3$face == "ace"]
deck3$value[deck3$face == "ace"] <- 14

head(deck3)
deck3$value[deck3$face == "ace"]

# hearts time
deck4 <- deck
deck4$value <- 0

head(deck4, 13)

deck4$value[deck4$suit == "hearts"] <- 1
deck4$value[deck4$suit == "hearts"]

queenOfSpades <- deck4$face == "queen" & deck4$suit == "spades"
deck4$value[queenOfSpades] <- 13
deck4[queenOfSpades, ]

#blackjack
deck5 <- deck

facecard <- deck5$face %in% c("king", "queen", "jack")
deck5[facecard, ]
deck5$value[facecard] <- 10
head(deck5, 13)

deck5$value[deck5$face == "ace"] <- NA
head(deck5, 13)


### Fixing it all up real purdy

as.environment("package:stats")
ls(emptyenv())
ls(globalenv())


show_env <- function(){
  list(ran.in = environment(), 
       parent = parent.env(environment()), 
       objects = ls.str(environment())) }

show_env()

DECK <- deck

deck <- deck[-1, ]
head(deck, 3)

deal <- function() {
  card <- deck[1, ]
  card <- deck[-1, ]
  card
}

deal <- function() {
  card <- deck[1, ]
  assign("deck", deck[-1, ], envir = globalenv())
  card
}

deal()

shuffle <- function(cards) {
  random <- sample(1:52, size = 52)
  cards[random, ]
}

head(deck, 3)
a <- shuffle(deck)
head(a, 3)


shuffle <- function(){
  random <- sample(1:52, size = 52)
  assign("deck", DECK[random, ], envir = globalenv())
}

shuffle()
deal()

setup <- function(deck) {
  DECK <- deck
  
  DEAL <- function() {
    card <- deck[1, ]
    assign("deck", deck[-1, ], envir = globalenv())
    card
  }
  
  SHUFFLE <- function() {
    random <- sample(1:52, size = 52)
    assign("deck", DECK[random, ], envir = globalenv())
  }
}


###################################tryin' this instead
setup <- function(deck) {
  DECK <- deck
  
  DEAL <- function() {
    card <- deck[1, ]
    assign("deck", deck[-1, ], envir = globalenv())
    card
  }
  
  SHUFFLE <- function(){
    random <- sample(1:52, size = 52)
    assign("deck", DECK[random, ], envir = globalenv())
  }
  
  list(deal = DEAL, shuffle = SHUFFLE)
}

cards <- setup(deck)

deal <- cards$deal
shuffle <- cards$shuffle

deal
shuffle

### interesting, here to reference the parent environment at run time
setup <- function(deck) {
  DECK <- deck
  
  DEAL <- function() {
    card <- deck[1, ]
    assign("deck", deck[-1, ], envir = parent.env(environment()))
    card
  }
  
  SHUFFLE <- function(){
    random <- sample(1:52, size = 52)
    assign("deck", DECK[random, ], envir = parent.env(environment()))
  }
  
  list(deal = DEAL, shuffle = SHUFFLE)
}

cards <- setup(deck)
deal <- cards$deal
shuffle <- cards$shuffle

rm(deck)
shuffle()
deal()
deal()

##################### that's it for cards, onto slot machine


```

```{r}
get_symbols <- function() {
  wheel <- c("DD", "7", "BBB", "BB", "B", "C", "0")
  sample(wheel, size = 3, replace = TRUE, 
         prob = c(0.03, 0.03, 0.06, 0.1, 0.25, 0.01, 0.52))
}

get_symbols()

play <- function() {
  symbols <- get_symbols()
  print(symbols)
  score(symbols)
}


symbols <- c("7", "7", "7")
symbols
symbols[1] == symbols[2] & symbols[2] == symbols[3]
length(unique(symbols) == 1)

same <- symbols[1] == symbols[2] & symbols[2] == symbols[3]

symbols <- c("B", "BBB", "BB")
all(symbols %in% c("B", "BB", "BBB"))

symbols <- c("B", "B", "B")
all(symbols %in% c("B", "BB", "BBB"))


payouts <- c("DD" = 100, "7" = 80, "BBB" = 40, "BB" = 25, 
             "B" = 10, "C" = 10, "0" = 0)
payouts

payouts["DD"]
unname(payouts["DD"])

same <- symbols[1] == symbols[2] && symbols[2] == symbols[3]
bars <- symbols %in% c("B", "BB", "BBB")


## this is where we are at now

# if (same) {
#   payouts <- c("DD" = 100, "7" = 80, "BBB" = 40, "BB" = 25, 
#                "B" = 10, "C" = 10, "0" = 0)
#   prize <- unname(payouts[symbols[1]])
# } else if (all(bars)) {
#   prize <- # assign $5
# } else {
#   # count cherries
#   prize <- # calculate a prize
# }
# 
# # count diamonds
# # double the prize if necessary

cherries <- sum(symbols == "C")

if (cherries == 2) {
  prize <- 5
} else if (cherries == 1) {
  prize <- 2
} else {
prize <- 0
}

c(0, 2, 5)
c(0, 2, 5)[cherries + 1]
cherries + 1

### our slot machine so far! this is fun :)
## adding comments to this now

# set up, or identifying case
same <- symbols[1] == symbols[2] && symbols[2] == symbols[3]
bars <- symbols %in% c("B", "BB", "BBB")

# obtaining a prize
if (same) {
  payouts <- c("DD" = 100, "7" = 80, "BBB" = 40, "BB" = 25, 
               "B" = 10, "C" = 10, "0" = 0)
  prize <- unname(payouts[symbols[1]])
} else if (all(bars)) {
  prize <- 5
} else {
  cherries <- sum(symbols == "C")
  prize <- c(0, 2, 5)[cherries + 1]
}
# aaand adjustments for those shiny diamonds
diamonds <- sum(symbols == "DD")
prize * 2^diamonds

# okay now lets put it under score

score <- function(symbols) {
  
  same <- symbols[1] == symbols[2] && symbols[2] == symbols[3]
  bars <- symbols %in% c("B", "BB", "BBB")
  
  if (same) {
    payouts <- c("DD" = 100, "7" = 80, "BBB" = 40, "BB" = 25, 
                 "B" = 10, "C" = 10, "0" = 0)
    prize <- unname(payouts[symbols[1]])
  } else if (all(bars)) {
    prize <- 5
  } else {
    cherries <- sum(symbols == "C")
    prize <- c(0, 2, 5)[cherries + 1]
  }
  
  diamonds <- sum(symbols == "DD")
  prize * 2 ^ diamonds
}

# remember the play function? it works now cause we set up score()

play()
one_play <- play()
one_play
# now it's time to clean it up
attributes(DECK)
attributes(one_play)


attr(one_play, "symbols") <- c("B", "0", "B")
attributes(one_play)
attr(one_play, "symbols")

play <- function() {
  symbols <- get_symbols()
  prize <- score(symbols)
  attr(prize, "symbols") <- symbols
  prize
}

play()
two_play <- play()


play <- function() {
  symbols <- get_symbols()
  structure(score(symbols), symbols = symbols)
}

three_play <- play()

symbols <- attr(one_play, "symbols")
symbols
symbols <- paste(symbols, collapse = " ")
symbols

prize <- one_play
string <- paste(symbols, prize, sep = "\n$")

string
cat(string)

slot_display <- function(prize) {
  symbols <- attr(prize, "symbols")
  symbols <- paste(symbols, collapse = " ")
  string <- paste(symbols, prize, sep = "\n$")
  cat(string)
}

slot_display(one_play)
slot_display(play())
#much better

class(one_play) <- "slots"
args(print)

print.slots <- function(x, ...) {
  cat("I'm using the print.slots method")
}

print(one_play)
rm(print.slots)

print.slots <- function(x, ...) {
  slot_display(x)
}

one_play


play <- function() {
  symbols <- get_symbols()
  structure(score(symbols), symbols = symbols, class = "slots")
}

class(play())
play()

methods(class = "factor")

### CH11
rolls <- expand.grid(die, die)
rolls
rolls$value <- rolls$Var1 + rolls$Var2
head(rolls, 3)


prob <- c("1" = 1/8, "2" = 1/8, "3" = 1/8, "4" = 1/8, "5" = 1/8, "6" = 3/8)

prob

rolls$prob1 <- prob[rolls$Var1]
head(rolls, 3)

rolls$prob2 <- prob[rolls$Var2]
head(rolls, 3)

rolls$prob <- rolls$prob1 * rolls$prob2
head(rolls, 3)

sum(rolls$value * rolls$prob)

wheel <- c("DD", "7", "BBB", "BB", "B", "C", "0")
combos <- expand.grid(wheel, wheel, wheel, stringsAsFactors = FALSE)
combos

get_symbols <- function(){
  wheel <- c("DD", "7", "BBB", "BB", "B", "C", "0")
  
  sample(wheel, size = 3, replace = TRUE, 
         prob = c(0.03, 0.03, 0.06, 0.1, 0.25, 0.01, 0.52))
}

prob <- c("DD" = 0.03, "7" = 0.03, "BBB" = 0.06, 
          "BB" = 0.1, "B" = 0.25, "C" = 0.01, "0" = 0.52)

combos$prob1 <- prob[combos$Var1]
combos$prob2 <- prob[combos$Var2]
combos$prob3 <- prob[combos$Var3]

head(combos, 3)

combos$prob <- combos$prob1 * combos$prob2 * combos$prob3
head(combos, 3)

sum(combos$prob)
symbols <- c(combos[1, 1], combos[1, 2], combos[1, 3])
score(symbols)

combos$prize <- NA
head(combos, 3)

for(i in 1:nrow(combos)) {
  symbols <- c(combos[i,1], combos[i,2], combos[i,3])
  combos$prize[i] <- score(symbols)
}

head(combos, 3)
sum(combos$prize * combos$prob)

########### NOW we account for Diamonds being wild

score <- function(symbols) {
  
  diamonds <- sum(symbols == "DD")
  cherries <- sum(symbols == "C")
  
  slots <- symbols[symbols != "DD"]
  same <- length(unique(slots)) == 1
  bars <- slots %in% c("B", "BB", "BBB")
  
  if (diamonds == 3) {
    prize <- 100
  } else if (same) {
    payouts <- c("7" = 80, "BBB" = 40, "BB" = 25,
                 "B" = 10, "C" = 10, "0" = 0)
    prize <- unname(payouts[slots[1]])
  } else if (all(bars)) {
    prize <- 5
  } else if (cherries > 0) {

    prize <- c(0, 2, 5)[cherries + diamonds + 1]
  } else {
    prize <- 0
  }
  
  prize * 2^diamonds
}

for (i in 1:nrow(combos)) {
  symbols <- c(combos[i, 1], combos[i, 2], combos[i, 3])
  combos$prize[i] <- score(symbols)
}

sum(combos$prize * combos$prob)

### playing again with while loops
no_mas_dineros <- function(start_with) {
  cash <- start_with
  n <- 0
  while (cash > 0) {
    cash <- cash - 1 + play()
    n <- n + 1
  }
  n
}

no_mas_dineros(100)

### repeat time
no_mas_dineros <- function(start_with) {
  cash <- start_with
  n <- 0
  repeat {
    cash <- cash - 1 + play()
    n <- n + 1
    if(cash <= 0) {
      break 
    }
  }
  n
}

no_mas_dineros(100)

########### 12.2
change_symbols <- function(vec){
  for (i in 1:length(vec)){
    if (vec[i] == "DD") {
      vec[i] <- "joker"
    } else if (vec[i] == "C") {
      vec[i] <- "ace"
    } else if (vec[i] == "7") {
      vec[i] <- "king"
    }else if (vec[i] == "B") {
      vec[i] <- "queen"
    } else if (vec[i] == "BB") {
      vec[i] <- "jack"
    } else if (vec[i] == "BBB") {
      vec[i] <- "ten"
    } else {
      vec[i] <- "nine"
    } 
  }
  vec
}

vec <- c("DD", "C", "7", "B", "BB", "BBB", "0")

change_symbols(vec)
many <- rep(vec, 100000)
system.time(change_symbols(many))

vec[vec == "0"]

vec[vec == "DD"] <- "joker"
vec[vec == "C"] <- "ace"
vec[vec == "7"] <- "king"
vec[vec == "B"] <- "queen"
vec[vec == "BB"] <- "jack"
vec[vec == "BBB"] <- "ten"
vec[vec == "0"] <- "nine"

change_vec <- function(vec) {
  vec[vec == "DD"] <- "joker"
  vec[vec == "C"] <- "ace"
  vec[vec == "7"] <- "king"
  vec[vec == "B"] <- "queen"
  vec[vec == "BB"] <- "jack"
  vec[vec == "BBB"] <- "ten"
  vec[vec == "0"] <- "nine"
  
  vec
}

change_vec2 <- function(vec){
  tb <- c("DD" = "joker", "C" = "ace", "7" = "king", "B" = "queen", 
          "BB" = "jack", "BBB" = "ten", "0" = "nine")
  unname(tb[vec])
}

system.time(change_vec(many))

##########12.4
winnings <- vector(length = 1000000)
for (i in 1:1000000) {
  winnings[i] <- play()
}

mean(winnings)

get_many_symbols <- function(n) {
  wheel <- c("DD", "7", "BBB", "BB", "B", "C", "0")
  vec <- sample(wheel, size = 3 * n, replace = TRUE,
                prob = c(0.03, 0.03, 0.06, 0.1, 0.25, 0.01, 0.52))
  matrix(vec, ncol = 3)
}

get_many_symbols(7)

play_many <- function(n) {
  symb_mat <- get_many_symbols(n = n)
  data.frame(w1 = symb_mat[,1], w2 = symb_mat[,2],
             w3 = symb_mat[,3], prize = score_many(symb_mat))
}

symbols <- matrix(
  c("DD", "DD", "DD", 
    "C", "DD", "0", 
    "B", "B", "B", 
    "B", "BB", "BBB", 
    "C", "C", "0", 
    "7", "DD", "DD"), nrow = 6, byrow = TRUE)

symbols

# time for a clean slot machine
score_many <- function(symbols) {
  cherries <- rowSums(symbols == "C")
  diamonds <- rowSums(symbols == "DD")
  
  prize <- c(0,2,5)[cherries + diamonds + 1]
  prize[!cherries] <- 0
  
  same <- symbols[, 1] == symbols[, 2] &
    symbols[, 2] == symbols[, 3]
  payoffs <- c("DD" = 100, "7" = 80, "BBB" = 40, "BB" = 25, "B" = 10,
               "C" = 10, "0" = 0)
  prize[same] <- payoffs[symbols[same, 1]]
  
  bars <- symbols == "B" | symbols == "BB" | symbols == "BBB"
  all_bars <- bars[, 1] & bars[, 2] & bars[, 3] & !same
  prize[all_bars] <- 5

  two_wilds <- diamonds == 2

  one <- two_wilds & symbols[, 1] != symbols[, 2] & 
    symbols[, 2] == symbols[, 3]
  two <- two_wilds & symbols[, 1] != symbols[, 2] & 
    symbols[, 1] == symbols[, 3]
  three <- two_wilds & symbols[, 1] == symbols[, 2] & 
    symbols[, 2] != symbols[, 3]
  
  prize[one] <- payoffs[symbols[one, 1]]
  prize[two] <- payoffs[symbols[two, 2]]
  prize[three] <- payoffs[symbols[three, 3]]
  
  one_wild <- diamonds == 1
  
  wild_bars <- one_wild & (rowSums(bars) == 2)
  prize[wild_bars] <- 5
  
  one <- one_wild & symbols[, 1] == symbols[, 2]
  two <- one_wild & symbols[, 2] == symbols[, 3]
  three <- one_wild & symbols[, 3] == symbols[, 1]
  prize[one] <- payoffs[symbols[one, 1]]
  prize[two] <- payoffs[symbols[two, 2]]
  prize[three] <- payoffs[symbols[three, 3]]
  
  unname(prize * 2^diamonds)
  
}

system.time(play_many(10000000))

play()
play_many(10)
#looks good :)
```

Now to wrap it all up! We got dice,
```{r}
myroll()
```

We got war,
```{r}
War <- setup(deck2)
WarDeal <- War$deal
WarShuffle <- War$shuffle
WarShuffle()
WarDeal()
```

We got blackjack,
```{r}
Blackjack <- setup(deck5)
BlackjackDeal <- Blackjack$deal
BlackjackShuffle <- Blackjack$shuffle
BlackjackShuffle()
BlackjackDeal()
```

We got hearts,
```{r}
Hearts <- setup(deck4)
HeartsDeal <- Hearts$deal
HeartsShuffle <- Hearts$shuffle
HeartsShuffle()
HeartsDeal()
```

and we got a slot machine, where you *might* win big!!
```{r}
play()
play_many(10)
```

So come on down to Vic's Casino for a fun time! 
