---
title: 'CA #10'
author: "Victoria Kincaid"
date: "10/29/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(moderndive)
library(infer)


bowl %>%
  summarise(p_red = mean(color == "red"))

bowl_sample_1 %>%
  specify(response = color, success = "red")

bowl_sample_1 %>%
  specify(response = color, success = "red") %>%
  generate(reps = 1000, type = "bootstrap")

sample_1_bootstrap <- bowl_sample_1 %>%
  specify(response = color, success = "red") %>%
  generate(reps = 1000, type = "bootstrap") %>%
  calculate(stat = "prop")

sample_1_bootstrap

percentile_ci_1 <- sample_1_bootstrap %>%
  get_confidence_interval(level = 0.95, type = "percentile")
percentile_ci_1

sample_1_bootstrap %>%
  visualise(bins = 15) +
  shade_confidence_interval(endpoints = percentile_ci_1) +
  geom_vline(xintercept = 0.42, linetype = "dashed")

bowl_sample_2 <- bowl %>% rep_sample_n(size = 50)
bowl_sample_2

sample_2_bootstrap <- bowl_sample_2 %>%
  specify(response = color, success = "red") %>%
  generate(reps = 1000, type = "bootstrap") %>%
  calculate(stat = "prop")

percentile_ci_2 <- sample_2_bootstrap %>%
  get_confidence_interval(level = 0.95, type = "percentile")
percentile_ci_2

######### 8.6
# why did i decide to do this at 11 at night, i'm
# already yawning my head off
mythbusters_yawn

mythbusters_yawn %>%
  group_by(group, yawn) %>%
  summarise(count = n())

mythbusters_yawn %>%
  specify(formula = yawn ~ group, success = "yes")

first_six_rows <- head(mythbusters_yawn)
first_six_rows

first_six_rows %>%
  sample_n(size = 6, replace = TRUE)

mythbusters_yawn %>%
  specify(formula = yawn ~group, success = "yes") %>%
  generate(reps = 1000, type = "bootstrap")

mythbusters_yawn %>%
  specify(formula = yawn ~group, success = "yes") %>%
  generate(reps = 1000, type = "bootstrap") %>%
  calculate(stat = "diff in props")

bootstrap_distribution_yawning <- mythbusters_yawn %>%
  specify(formula = yawn ~group, success = "yes") %>%
  generate(reps = 1000, type = "bootstrap") %>%
  calculate(stat = "diff in props", order = c("seed", "control"))

bootstrap_distribution_yawning

visualise(bootstrap_distribution_yawning) +
  geom_vline(xintercept = 0)

bootstrap_distribution_yawning %>%
  get_confidence_interval(type = "percentile", level = 0.95)

obs_diff_in_props <- mythbusters_yawn %>%
  specify(formula = yawn ~ group, success = "yes") %>%
  calculate(stat = "diff in props", order = c("seed", "control"))

obs_diff_in_props

myth_ci_se <- bootstrap_distribution_yawning %>%
  get_confidence_interval(type = "se", point_estimate = obs_diff_in_props)

myth_ci_se

```

```{r}

visualise(bootstrap_distribution_yawning) +
  geom_vline(xintercept = 0)+
  shade_ci(endpoints = myth_ci_se,color = "black", fill = "khaki")
```

Alas, looking at our image here we can see that it straddles over that pesky zero. From here we can say with 95% confidence that there is no associated effect of being exposed to a yawning individual on whether one yawns. I must be a statistical anomaly cause I've been yawning this whole time or I need to crash. One of the three I'm sure.